version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@8.2.1
  aws-cli: circleci/aws-cli@3.1.4
jobs:
  continuous-integration:
    docker:
      - image: cimg/base:stable
    resource_class: medium
    steps:
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true

      - aws-cli/setup

      - checkout
      - run:
          name: auth to aws ecr
          command: aws ecr get-login-password --region .us-east-1 | docker login --username AWS --password-stdin 566373416292.dkr.ecr.us-east-1.amazonaws.com

      - run:
          name: build docker image
          command: docker build -t 566373416292.dkr.ecr.us-east-1.amazonaws.com/depression-classification:latest .

      - run:
          name: pull image from private repository
          command: docker push 566373416292.dkr.ecr.us-east-1.amazonaws.com/depression-classification:latest

  #     - run:
  # continuous-delivery:
  #   machine: true
  #   resource_class: deep-learning-01/dl-ineuron
  #   steps:
  #     - aws-cli/setup

  #     - run:
  #         name: auth to aws ecr
  #         command: aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 566373416292.dkr.ecr.ap-south-1.amazonaws.com

  #     - run:
  #         name: pull image from private repository
  #         command: docker pull 566373416292.dkr.ecr.ap-south-1.amazonaws.com/human-action-recognition:latest
    
  #     - run:
  #         name: run image
  #         command: docker run -d -e AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} -e AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} -e AWS_DEFAULT_REGION=${AWS_REGION} -p 8080:8080 566373416292.dkr.ecr.ap-south-1.amazonaws.com/human-action-recognition:latest
workflows:
  CICD:
    jobs:
      - continuous-integration
      # - continuous-delivery:
      #     requires:
      #     - continuous-integration
      
